# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OjoMetropolitano' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OjoMetropolitano

pod 'GoogleMaps'

pod 'Firebase/Core'
pod 'Firebase/Messaging'

  # target 'OjoMetropolitano-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  #   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  #   pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  #   pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  #   pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  # end

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  target 'OjoMetropolitanoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
